### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Aerodlyn** [mattir/dvp-u3-constellations#1]
Overall, great job! I did notice one slight difference between what you have and what the solution code has:

https://github.com/mattir/dvp-u3-constellations/blob/d18885b3203d2eb8a7a5eb719c124e6c88c1680a/orion-constellation/constellation.py#L72-L76

`add_subplot` returns an `axes` object which you would then call `scatter` on as it will have the correct scale that you set using the `add_subplot` call. If you use `plt.scatter`, that call might have no effect on the figure you just generated due to how Matplotlib handles plot generation. So, your code might look something like this:

```
fig_2d = plt.figure()
constellation2d = fig_2d.add_subplot(1,1,1)
constellation2d.scatter(x,y)
plt.show()
```

Also, I would recommend not using such a dark color as a background for your figures unless you change the text color of the labels to a lighter color such as white.

**Comment by mattir** [comment]
Thank you for the feedback. I followed a similar method to the one you described for the 3D figure, but didn't associate that with the 2D scatter plot. The instructions didn't make it as obvious that that was the expected way for the 2D figure. The instructions for the 3D figure made that process more apparent. I'll keep this in mind going forward though.
